version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: 1on1re_dw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: etl_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

  pentaho:
    image: knowbi/pentaho:9.3
    container_name: etl_pentaho
    ports:
      - "8080:8080"
    environment:
      PENTAHO_DI_JAVA_OPTIONS: "-Xms512m -Xmx2048m"
    volumes:
      - ./pentaho:/home/pentaho/.pentaho

  pgadmin:
    image: dpage/pgadmin4
    container_name: etl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etl.com
      PGADMIN_DEFAULT_PASSWORD: etladmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  metabase_data:
  pgadmin_data:
